#cloud-config
autoinstall:
  version: 1
  apt:
    mirror-selection:
      primary:
        - uri: "https://ftp.kaist.ac.kr/ubuntu/"
          arches: [amd64]
        - uri: "https://mirror.kakao.com/ubuntu/"
          arches: [amd64]
        - uri: "http://archive.ubuntu.com/ubuntu"
          arches: [amd64]
    fallback: abort

  storage:
    layout:
      name: direct
    # 특정 디스크 매칭이 실패할 경우를 대비해 
    # 일반적인 설정을 권장하거나 match 조건을 확인하세요.

  identity:
    hostname: main-1
    username: walter
    password: "$6$m9rLgoAUUIzlB6vG$ZoPRCs0EbxtDTC6gBzRTxSMOf3p6MC6cXAw9V8A.csjFBii/yucC3rVE5P7tPgwVLHwHANgmr9EehbIcvZBvU0"
  
  ssh:
    install-server: true
    allow-pw: true
  
  # 추가 패키지 설치가 필요하다면 아래 형식을 사용하세요.
  # 없으면 packages 섹션 자체를 삭제해야 합니다.
  packages:
    - vim
    - curl

  codecs:
    install: true
  
  drivers:
    install: true
  
  # Desktop 버전 설치가 아닌 Server 버전 설치라면 
  # oem, codecs 설정은 무시될 수 있습니다.
  oem:
    install: auto
  
  kernel-crash-dumps:
    enabled: true
  
  timezone: "Asia/Seoul"
  locale: ko_KR.UTF-8
  keyboard:
    layout: kr

  updates: all

  # 24.04에서는 설치 프로그램 업데이트가 문제를 일으키는 경우가 많습니다.
  # 에러가 지속되면 아래 refresh-installer 부분을 false로 바꾸어 보세요.
  refresh-installer:
    update: false

  shutdown: reboot
